// Real product data from Captain Maid scraping (2026-07-06)
// Source: captain-maid.com + HomePro

export const CAPTAIN_MAID_PRODUCTS = [
  {
    id: 'floor-cleaner-floral-900ml',
    sku: '1313735',
    name: 'Floor Cleaner - Floral',
    nameThb: 'น้ำยาทำความสะอาดพื้น CAPTAIN MAID 900 มล. FLORAL',
    description: 'Professional grade floor cleaner with natural ingredients, safe for all floor types',
    descriptionThb: 'น้ำยาทำความสะอาดพื้นระดับมืออาชีพ มีส่วนผสมจากธรรมชาติ ปลอดภัยสำหรับพื้นทุกประเภท',
    variant: 'Floral',
    price: 5.84, // ฿119 / 20.4 (approx USD)
    priceThb: 119,
    originalPrice: 6.32,
    originalPriceThb: 129,
    discountPrice: 4.85,
    discountPriceThb: 99,
    image: '/images/products/floor-cleaner-floral.svg',
    category: 'Floor Cleaners',
    categoryThb: 'น้ำยาทำความสะอาดพื้น',
    rating: 4.8,
    reviewCount: 245,
    soldCount: 1250,
    inStock: true,
    featured: true,
    keyClaims: ['99.9% germ elimination', 'Safe for kids & pets', 'Natural ingredients'],
    ingredients: 'Water, Natural plant extract, Surfactant',
    usage: 'Dilute 1:10 with water, Apply to floor with mop, Let dry',
    barcode: '8850333111111',
    size: '900ml',
  },
  {
    id: 'floor-cleaner-teatree-900ml',
    sku: '1313716',
    name: 'Floor Cleaner - Tea Tree',
    nameThb: 'น้ำยาทำความสะอาดพื้น CAPTAIN MAID 900 มล. TEA TREE',
    description: 'Professional grade floor cleaner with tea tree oil, naturally antibacterial',
    descriptionThb: 'น้ำยาทำความสะอาดพื้นระดับมืออาชีพ มีน้ำมันแช่ม จึงมีคุณสมบัติต้านแบคทีเรีย',
    variant: 'Tea Tree',
    price: 5.84,
    priceThb: 119,
    originalPrice: 6.32,
    originalPriceThb: 129,
    discountPrice: 4.85,
    discountPriceThb: 99,
    image: '/images/products/floor-cleaner-teatree.svg',
    category: 'Floor Cleaners',
    categoryThb: 'น้ำยาทำความสะอาดพื้น',
    rating: 4.7,
    reviewCount: 189,
    soldCount: 950,
    inStock: true,
    featured: true,
    keyClaims: ['Antibacterial', 'Antifungal', 'Natural tea tree oil'],
    ingredients: 'Water, Tea tree oil, Plant extract, Surfactant',
    usage: 'Dilute 1:10 with water, Mop floor, Air dry',
    barcode: '8850333111128',
    size: '900ml',
  },
  {
    id: 'floor-cleaner-lavender-900ml',
    sku: '1313729',
    name: 'Floor Cleaner - Lavender',
    nameThb: 'น้ำยาทำความสะอาดพื้น CAPTAIN MAID 900 มล. LAVENDER',
    description: 'Aromatic floor cleaner with relaxing lavender scent, gentle formula',
    descriptionThb: 'น้ำยาทำความสะอาดพื้นหอมกลิ่นลาเวนเดอร์ สูตรอ่อนโยนสำหรับพื้น',
    variant: 'Lavender',
    price: 5.84,
    priceThb: 119,
    originalPrice: 6.32,
    originalPriceThb: 129,
    discountPrice: 4.85,
    discountPriceThb: 99,
    image: '/images/products/floor-cleaner-lavender.svg',
    category: 'Floor Cleaners',
    categoryThb: 'น้ำยาทำความสะอาดพื้น',
    rating: 4.6,
    reviewCount: 156,
    soldCount: 820,
    inStock: true,
    keyClaims: ['Aromatic', 'Gentle on floors', 'Natural lavender'],
    ingredients: 'Water, Lavender oil, Plant extract, Surfactant',
    usage: 'Dilute 1:10, Sweep first, Mop with solution',
    barcode: '8850333111135',
    size: '900ml',
  },
];

export type Product = (typeof CAPTAIN_MAID_PRODUCTS)[0];
