// Real product data from Captain Maid scraping (2026-07-06)
// Source: captain-maid.com + HomePro

export const CAPTAIN_MAID_PRODUCTS = [
  {
    id: 'floor-cleaner-floral-900ml',
    sku: '1313735',
    name: 'Natural Floor Cleaner',
    nameThb: 'น้ำยาทำความสะอาดพื้น CAPTAIN MAID 900 มล.',
    description: 'Eco-friendly formula with natural ingredients, perfect for fresh mornings',
    descriptionThb: 'สูตรที่เป็นมิตรกับสิ่งแวดล้อมที่มีส่วนผสมจากธรรมชาติ',
    variant: 'Spring Fresh / Green',
    color: '#00AA44',
    colorName: 'Green',
    price: 5.84,
    priceThb: 119,
    originalPrice: 6.32,
    originalPriceThb: 129,
    discountPrice: 4.85,
    discountPriceThb: 99,
    image: '/images/products/green-bottle.svg',
    category: 'Floor Cleaners',
    categoryThb: 'น้ำยาทำความสะอาดพื้น',
    rating: 4.8,
    reviewCount: 245,
    soldCount: 1250,
    inStock: true,
    featured: true,
    keyClaims: ['Eco-friendly', 'Natural ingredients', '99.9% germ elimination'],
    ingredients: 'Water, Natural plant extract, Surfactant',
    usage: 'Dilute 1:10 with water, Apply to floor with mop, Let dry',
    barcode: '8850333111111',
    size: '900ml',
  },
  {
    id: 'floor-cleaner-teatree-900ml',
    sku: '1313716',
    name: 'Tea Tree Floor Cleaner',
    nameThb: 'น้ำยาทำความสะอาดพื้น CAPTAIN MAID 900 มล.',
    description: 'Antibacterial powerhouse with natural tea tree oil protection',
    descriptionThb: 'อำนาจต้านแบคทีเรียที่แข็งแกร่งด้วยน้ำมันแช่มธรรมชาติ',
    variant: 'Floral Breeze / Pink',
    color: '#FF1493',
    colorName: 'Pink',
    price: 5.84,
    priceThb: 119,
    originalPrice: 6.32,
    originalPriceThb: 129,
    discountPrice: 4.85,
    discountPriceThb: 99,
    image: '/images/products/pink-bottle.svg',
    category: 'Floor Cleaners',
    categoryThb: 'น้ำยาทำความสะอาดพื้น',
    rating: 4.7,
    reviewCount: 189,
    soldCount: 950,
    inStock: true,
    featured: true,
    keyClaims: ['Antibacterial', 'Antifungal', 'Natural tea tree oil'],
    ingredients: 'Water, Tea tree oil, Plant extract, Surfactant',
    usage: 'Dilute 1:10 with water, Mop floor, Air dry',
    barcode: '8850333111128',
    size: '900ml',
  },
  {
    id: 'floor-cleaner-lavender-900ml',
    sku: '1313729',
    name: 'Lavender Floor Cleaner',
    nameThb: 'น้ำยาทำความสะอาดพื้น CAPTAIN MAID 900 มล.',
    description: 'Luxurious lavender scent for a spa-like home experience',
    descriptionThb: 'กลิ่นลาเวนเดอร์หรูหราสำหรับประสบการณ์บ้านแบบสปา',
    variant: 'Premium Aroma / Purple',
    color: '#7B2CBF',
    colorName: 'Purple',
    price: 5.84,
    priceThb: 119,
    originalPrice: 6.32,
    originalPriceThb: 129,
    discountPrice: 4.85,
    discountPriceThb: 99,
    image: '/images/products/purple-bottle.svg',
    category: 'Floor Cleaners',
    categoryThb: 'น้ำยาทำความสะอาดพื้น',
    rating: 4.6,
    reviewCount: 156,
    soldCount: 820,
    inStock: true,
    keyClaims: ['Aromatic', 'Gentle on floors', 'Natural lavender'],
    ingredients: 'Water, Lavender oil, Plant extract, Surfactant',
    usage: 'Dilute 1:10, Sweep first, Mop with solution',
    barcode: '8850333111135',
    size: '900ml',
  },
];

export type Product = (typeof CAPTAIN_MAID_PRODUCTS)[0];
